### ISSUE TITLE
How to view html files

### ISSUE THREAD

**Issue by KST0NE** [KST0NE/Assignment-8#2]
I know you have gone over this a few times but I'm having trouble getting it to stick. How do we view html files such as the one I created here for my presentation from once they are on github?

**Comment by mdscheuerell** [comment]
You need to prepend the URL with `https://htmlpreview.github.io/?`. So, for example,

https://htmlpreview.github.io/?https://github.com/KST0NE/Assignment-8/blob/main/Assignment8.html

In this case, I tried the above method and it's only showing a black slide. Andrea had this problem and I think she solved it by updating R and R Markdown.

Also note that you can alway double-click on the `.html` file in your local folder/directory and it should open automatically in your web browser.

**Comment by KST0NE** [comment]
That didn't seem to work, I am able to view it just fine on my computer by clicking on it from the directory. But that doesn't allow you to see it unless you put everything on yours, correct?

**Comment by mdscheuerell** [comment]
True-I cannot see the rendered version, but all I really need in this case is the `.Rmd` file because I can see the bullet points there. And I can view your pic directly from the repo (which is a great photo, BTW!).
